# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/new-test
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - new-test-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - new-test 

      - run: pwd; ls -la; cd /new-test; mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/Users/aaibedul/.m2
          key: new-test-{{ checksum "pom.xml" }}

# run tests!
      - run: mvn -Dtest=StepsDefinition test
