# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/new-test/comfreeNowapitest
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - new-test/comfreeNowapitest-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - new-test/comfreeNowapitest

      - run: pwd; cd comfreeNowapitest; pwd; ls -la; mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/new-test/.m2
          key: new-test/comfreeNowapitest-{{ checksum "pom.xml" }}

# run tests!
      - run: pwd; cd comfreeNowapitest; pwd; mvn -Dtest=StepsDefinition test
